### ISSUE TITLE
1 bug and 1 suggestion

### ISSUE THREAD

**Issue by studDUGY** [Twentysix26/Red-DiscordBot#1]
Hello,

Very nice bot! Had lots of fun playing around with it with me and my friends. However, I have one bug (well at least I think it's one) and one suggestion:

- The "!name" command adds a "." before and a "()" after the name entered. For instance, if I called mine "SuperBot", the end result turns out to be ".SuperBot()". Just very slightly annoying (OCD and proud, haha).

- It would be nice if we could make the bot auto-join a voice channel automatically (with an instant invite link). Right now, the only way I can make it work without having my browser open is to open the bot's account in my browser, connect it to the desired voice channel, run the bot, play a YouTube song, and then close my browser. EDIT: Nevermind, it actually works fine. I'm just retarded. xD

Other than that, great bot! Loooots of fun with it.

**Comment by Twentysix26** [comment]
Hi,
the name stuff is a design choice, part of the whole Transistor theme but it's perfectly natural that some people might not like it.
 I'm probably taking it out soon entirely or at least make it optional in the settings since I don't like how it's forced upon the user. I'm glad you're liking the bot :) Stay tuned for updates.

**Comment by Twentysix26** [comment]
Feature has been taken out in the latest update. No more forced name format.
