### ISSUE TITLE
Adding Google Play Music Support

### ISSUE THREAD

**Issue by cj-zeiger** [Twentysix26/Red-DiscordBot#31]
I've thrown together a prototype for google play music integration.

I was wondering if we could create a new feature branch so I could get some feedback and gauge interest?

**Comment by cj-zeiger** [comment]
So I'm going to take that as a no then ...

**Comment by Twentysix26** [comment]
Sorry for the late-ish answer.
I've taken a quick look at your fork and the library that it's using. Correct me if I'm wrong but it seems like it's based on urllib. Like I said in some other issues (see cleverbot) I can't put it in my bot, as it would make it non-responsive while it's being used. That's why I use aiohttp in my code (except for one  function that it's still using requests).
So it would probably need some rewrite to integrate it in a async friendly way.

Also, I don't think I've ever got requests to support google play music before, people mostly ask for services like soundcloud, and I'd rather work on the most requested features.
Thanks for your interest in contributing

**Comment by cj-zeiger** [comment]
True, I'm used to java threads where coroutines don't exist.
