### ISSUE TITLE
Suggestion: auto delete messages after x seconds

### ISSUE THREAD

**Issue by Dazzuh** [Twentysix26/Red-DiscordBot#37]
This could be useful to prevent the chat getting cluttered. 

Having it as an option would be nice, with a configurable timer.
also, deleting both the bots messages and (some) command messages sent by users

**Comment by Mikegrann** [comment]
I've implemented something that could be adapted to this over at my fork https://github.com/Mikegrann/Red-DiscordBot/commit/de2ac7c0cce4e3b75fc696ec5eccd3a226154e6b . Currently I just use it to automatically delete a handful of messages like !help responses after a few seconds (to keep the channel clear of !help requests and responses that can be temporary in chat because they're permanent in private messages).

Now it would be a simple matter to be able to automatically delete any other messages the bot posts (you'll notice the bot already does this for some audio commands). I just have a hard time seeing the appeal. What kinds of things, *specifically*, were you thinking about having disappear automatically?

**Comment by Dazzuh** [comment]
Basically just the bots responses and the users command message, simply to keep the level of messages between users and the bot down to a minimum but still being able to use it as much as we like.

**Comment by Mikegrann** [comment]
Mmmmm... I see what you're going for here. It's doable, but I see some problems with it. First, it would require a fairly ugly rewrite in order to also delete the user's message alongside the bot's response. Still doable, but it'll be bloated and structured in a way I wouldn't like. Second, between the time that the bot sends the message and the time that it autodeletes it, there's a task sitting there scheduling that deletion to happen at some time in the future. If the time before deletion is too long and many messages accumulate, that may become a problem (haven't tested it). But if the time before deletion is too short, then other members might miss out on parts of the conversation because it disappears too quickly.

I just have a hard time seeing this working out well. Maybe another dev who understands its use better will come along and try to implement it. For now I'd suggest making use of !cleanup to get rid of messages whenever you feel things have become cluttered. 

I'll look into making a new !cleanup variant that allows you to remove commands and bot responses from chat while keeping normal messages. I'll also be on the lookout for other opportunities to reduce clutter, like maybe deleting the user message for custom commands while maintaining the bot response, or perhaps deleting some simple responses that wouldn't be missed shortly after being used, like !flip.

**Comment by Dazzuh** [comment]
We used to use it on a bot for plug.dj, it worked really well on there as theres only one chat so there isn't an alternative room you can use for bot commands and to keep the clutter from the main room, ofcourse there was some situations where people would miss messages from the bot, but ultimately it came down to if you didn't see the bot's reply then the message likely wasn't meant for you anyway, as it would delete non-essential replies and direct replies to user commands but keep any message up that was meant to be viewed by more than just one or two people.

**Comment by Prospy006** [comment]
Err, I have this problem too...

**Comment by Prospy006** [comment]
Err, I have this problem too...

**Comment by Jackenmen** [comment]
Please don't necro old issues. If you have found some bug, or have a feature request, make a new issue instead. If you need help with setting up Red, ask on [our discord server](https://discord.gg/red)

For your information, current version of Red does have a way to set a delete delay for command messages with `[p]set deletedelay` (`[p]` is your prefix).
