### ISSUE TITLE
More informative message when playing youtube videos

### ISSUE THREAD

**Issue by rookwood101** [Twentysix26/Red-DiscordBot#7]
`Playing youtube video <youtube video id> requested by <username>` is the current message.
I propose something like:
`Playing youtube video "<youtube video title>" requested by <username>`
(https://www.youtube.com/watch?v=<youtube video id>)

It indicates the name of the video and provides a url, much more convenient!

**Comment by Twentysix26** [comment]
I chose to send only the ID instead of the link because Discord's code tags are a bit odd and they still post the preview of a link enclosed in them. I just noticed this though:
if you enclose ONLY a link in the code tags Discord won't show the preview.
\`https://www.youtube.com/watch?v=XXXX test test\` This shows the preview
\`https://www.youtube.com/watch?v=XXXX \` This doesn't
So I'll make the change soon.

You've got a point about the title. I'm redoing the whole audio system soon anyway, code-wise is a mess.

**Comment by KuroMajutsu** [comment]
<code>client.send_message(message.channel, "\`Playing youtube video {} requested by {}\`".format(youtubeparser.getTitle(currentPlaylist.playlist[currentPlaylist.current]), message.author.name))</code>

This line will say the youtube video's title. Replace line 965 in red.py with this. It's half the solution, atleast.

instead of 
<code>Playing youtube video \<youtube video id\> requested by \<username\></code> itll say
<code>Playing youtube video \<video title\> requested by \<username\></code>

**Comment by Asute** [comment]
Added in v2 with SoundCloud support!
